services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8443:8443"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /etc/letsencrypt/live/${DOMAIN_NAME}:/etc/letsencrypt/live/${DOMAIN_NAME}:ro
      - /etc/letsencrypt/archive/${DOMAIN_NAME}:/etc/letsencrypt/archive/${DOMAIN_NAME}:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8443/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata: